USE [WVMSDB]
GO
IF OBJECT_ID('dbo.TBL_WVMSACCOUNTLOGIN', 'U') IS NOT NULL 
BEGIN
  DROP TABLE dbo.[TBL_WVMSACCOUNTLOGIN]
END
GO
CREATE TABLE dbo.[TBL_WVMSACCOUNTLOGIN]
(
	[ID] int NOT NULL IDENTITY(1,1),
	[UserName] varchar (50) NOT NULL,
	[Password] varchar (50) NULL,
	[IS_ACTIVE] BIT NOT NULL DEFAULT(1),
	[VERSION] INT NOT NULL DEFAULT(1),
	[LAST_MODIFIED_AT] DATETIME NOT NULL DEFAULT(GETDATE()), 
	[LAST_MODIFIED_BY] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_TBL_WVMSACCOUNTLOGIN] PRIMARY KEY ([ID]),
	CONSTRAINT [UQ_TBL_WVMSACCOUNTLOGIN_TEAM_ID_NAME] UNIQUE ([UserName])
)
GO

