USE [WVMSDB]
GO
IF OBJECT_ID('dbo.TBL_VEHICLEPORTPASS', 'U') IS NOT NULL 
BEGIN
  DROP TABLE dbo.[TBL_VEHICLEPORTPASS]
END
GO

CREATE TABLE [dbo].[TBL_VEHICLEPORTPASS](
	[ID] int IDENTITY(1,1) NOT NULL,
	[LicensesPlateNo] int NOT NULL,
	[PortPassInfo]varchar(50) NULL,
	[ExpiryDate] date NULL,
	[Remarks] VARCHAR(150) NULL,
	[IS_ACTIVE] BIT NOT NULL,
	[COMMENTS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL DEFAULT (1),
	[LAST_MODIFIED_AT] DATETIME NULL DEFAULT (GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(20) NOT NULL,
 CONSTRAINT [PK_TBL_VEHICLEPORTPASS] PRIMARY KEY ([ID]), 
 CONSTRAINT [FK_TBL_VEHICLEPORTPASS_ID_TBL_VEHICLE_VehicleID] FOREIGN KEY ([ID]) REFERENCES [TBL_VEHICLE]([vehicleID]),
 CONSTRAINT [FK_TBL_VEHICLEPORTPASS_LicensesPlateNo_TBL_VEHICLE_LicPlate] FOREIGN KEY ([LicensesPlateNo]) REFERENCES [TBL_VEHICLE]([vehicleID])
 )
GO


