USE [WVMSDB]
GO
IF OBJECT_ID('dbo.TBL_DRIVERPORTPASS','U') IS NOT NULL
BEGIN
	DROP TABLE [dbo].[TBL_DRIVERPORTPASS];
END
GO
CREATE TABLE [dbo].[TBL_DRIVERPORTPASS]
(
	[DriverId] int IDENTITY(1,1) NOT NULL,
	[PortPassInfo] varchar(50) NULL,
	[ExpiryDate] date NULL,
	[Remarks] varchar(150) NULL,
	[IS_ACTIVE] BIT NOT NULL,
	[COMMENTS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL DEFAULT (1),
	[LAST_MODIFIED_AT] DATETIME NULL DEFAULT (GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(20) NOT NULL,
	CONSTRAINT [PK_TBL_DRIVERPORTPASS] PRIMARY KEY([DriverId]),
	CONSTRAINT[FK_TBL_DRIVERPORTPASS_DriverId_TBL_DRIVER_DriverId] FOREIGN KEY([DriverId]) REFERENCES [TBL_DRIVER]([DriverId])
	--CONSTRAINT[FK_TBL_DRIVERPORTPASS_PortPassInfo_TBL_DRIVER_PortPassInfo] FOREIGN KEY([PortPassInfo]) REFERENCES [TBL_DRIVER]([DriverId]),
	--CONSTRAINT[FK_TBL_DRIVERPORTPASS_ExpiryDate_TBL_DRIVER_PassportExpiryDate] FOREIGN KEY([ExpiryDate]) REFERENCES [TBL_DRIVER]([DriverId])
)
GO


