USE [WVMSDB]
GO
IF OBJECT_ID('dbo.TBL_VehicleLog','U') IS NOT NULL
BEGIN
	DROP TABLE [dbo].[TBL_VehicleLog];
END
GO
CREATE TABLE [dbo].[TBL_VehicleLog](
	[ID] INT NOT NULL IDENTITY(1,1),
	[LICENSESPLATENO] INT,
	[DRIVERID] INT,
	[MISSIONID] INT,
	[MOVEMENTTYPE] VARCHAR(50),
	[DATE] DATE,
	[TIME] TIME,
	[PURPOSE] VARCHAR(150),
	[REMARKS] VARCHAR(150),
	[IS_ACTIVE] BIT NOT NULL,
	[COMMENTS] VARCHAR(20) NULL,
	[VERSION] INT NOT NULL DEFAULT (1),
	[LAST_MODIFIED_AT] DATETIME NULL DEFAULT (GETDATE()),
	[LAST_MODIFIED_BY] VARCHAR(20) NOT NULL,
	CONSTRAINT [PK_TBL_VehicleLog] PRIMARY KEY ([ID]),
	CONSTRAINT [UQ_TBL_VehicleLog_LICENSESPLATENO_DRIVERID_MISSIONID] UNIQUE ([LICENSESPLATENO],[DRIVERID],[MISSIONID]),
	CONSTRAINT [FK_TBL_VehicleLog_LICENSESPLATENO_TBL_VEHICLE_VehicleID] FOREIGN KEY ([LICENSESPLATENO]) REFERENCES TBL_VEHICLE([VehicleID]),
	CONSTRAINT [FK_TBL_VehicleLog_DRIVERID_TBL_DRIVER_DriverId] FOREIGN KEY ([DriverId]) REFERENCES TBL_DRIVER([DriverId]),
	CONSTRAINT [FK_TBL_VehicleLog_MISSIONID_TBL_Mission_ID] FOREIGN KEY ([MISSIONID]) REFERENCES TBL_Mission ([MissionId])
)
GO